---
apiVersion: v1
kind: pack
spec:
  disabled: false
  name: windows_powershell_events
  queries:
  - description: Powershell script blocks reconstructed to their full script content,
      this table requires script block logging to be enabled. - ATT&CK T1086,T1064
    interval: 3600
    name: powershell_events_script_blocks
    query: powershell_events_script_blocks
    removed: false
  targets:
    labels: null
    teams: null
---
apiVersion: v1
kind: query
spec:
  description: Powershell script blocks reconstructed to their full script content,
    this table requires script block logging to be enabled. - ATT&CK T1086,T1064
  name: powershell_events_script_blocks
  query: select * from powershell_events;
